name: paper
description: Record your beautiful life.

publish_to: 'none'

version: 1.0.0+6

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^2.0.0-dev.9
  graphql_flutter: ^5.1.0
  shared_preferences: ^2.0.15
  fluttertoast: ^8.0.9
  js: ^0.6.4
  rxdart: ^0.27.5
  intl: ^0.17.0
  nanoid: ^1.0.0
  pointer_interceptor: ^0.9.3+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  assets:
    - editor/dist/
    - editor/dist/assets/
